package payments

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"sync"
)

// MockSignatureHeader carries the webhook signature for the mock provider.
const MockSignatureHeader = "X-Mock-Signature"

// MockProvider is the deterministic sandbox adapter (spec §31.29: build
// against mock adapters when blocked on external credentials). It is
// selected whenever PAYMENT_PROVIDER=mock or PAYSTACK_SECRET_KEY is unset.
// Webhook verification uses HMAC-SHA256 over the exact raw body — a
// different algorithm than Paystack's HMAC-SHA512 but the identical code
// path, so production cutover changes no control flow.
type MockProvider struct {
	secret []byte
	mu     sync.Mutex
	// completed records references whose payment the sandbox has "collected"
	// (via SignWebhookPayload), so VerifyPayment stays consistent.
	completed map[string]bool
}

// NewMockProvider builds the sandbox adapter. secret is the webhook signing
// secret (MOCK_WEBHOOK_SECRET; a documented dev-only default exists).
func NewMockProvider(secret string) *MockProvider {
	return &MockProvider{secret: []byte(secret), completed: map[string]bool{}}
}

// Name implements PaymentProvider.
func (m *MockProvider) Name() string { return "mock" }

// InitializePayment returns a fake hosted authorization URL; nothing leaves
// the process. The reference is generated by the caller (payment row) — the
// mock echoes it back like a provider would.
func (m *MockProvider) InitializePayment(_ context.Context, req InitializePaymentRequest) (InitializePaymentResult, error) {
	if req.AmountMinor <= 0 || req.Reference == "" {
		return InitializePaymentResult{}, fmt.Errorf("payments: mock initialize requires amount and reference")
	}
	return InitializePaymentResult{
		Reference:        req.Reference,
		AuthorizationURL: "https://sandbox.payments.guideghana.test/authorize/" + req.Reference,
	}, nil
}

// VerifyPayment reports "success" once SignWebhookPayload completed the
// reference, otherwise "pending".
func (m *MockProvider) VerifyPayment(_ context.Context, providerRef string) (VerifyResult, error) {
	m.mu.Lock()
	done := m.completed[providerRef]
	m.mu.Unlock()
	status := "pending"
	if done {
		status = "success"
	}
	return VerifyResult{Reference: providerRef, Status: status}, nil
}

// Refund always succeeds in the sandbox.
func (m *MockProvider) Refund(_ context.Context, req RefundRequest) (RefundResult, error) {
	return RefundResult{Reference: "mockrefund_" + randomHex(8), Status: "success"}, nil
}

// CreateTransfer always succeeds in the sandbox (payout phase).
func (m *MockProvider) CreateTransfer(_ context.Context, req TransferRequest) (TransferResult, error) {
	return TransferResult{Reference: "mocktransfer_" + randomHex(8), Status: "success"}, nil
}

// VerifyWebhook authenticates the mock webhook: X-Mock-Signature must equal
// hex(HMAC-SHA256(rawBody, secret)), compared in constant time.
func (m *MockProvider) VerifyWebhook(headers http.Header, rawBody []byte) error {
	got := headers.Get(MockSignatureHeader)
	want := m.Sign(rawBody)
	if got == "" || !hmac.Equal([]byte(got), []byte(want)) {
		return ErrBadSignature
	}
	return nil
}

// Sign computes the mock webhook signature for rawBody (hex HMAC-SHA256).
// Exported so tests and local tooling can drive the webhook endpoint exactly
// like a real provider delivery.
func (m *MockProvider) Sign(rawBody []byte) string {
	h := hmac.New(sha256.New, m.secret)
	h.Write(rawBody)
	return hex.EncodeToString(h.Sum(nil))
}

// SignWebhookPayload builds the success webhook delivery for a reference
// (body + signature) and marks the reference completed for VerifyPayment.
// This is the sandbox's "customer paid" trigger — tests POST body+signature
// to /api/v1/webhooks/payments/mock.
func (m *MockProvider) SignWebhookPayload(reference string) (body []byte, signature string) {
	body = []byte(fmt.Sprintf(
		`{"event":"charge.success","data":{"reference":%q,"status":"success"}}`, reference))
	m.mu.Lock()
	m.completed[reference] = true
	m.mu.Unlock()
	return body, m.Sign(body)
}

func randomHex(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(fmt.Sprintf("payments: entropy: %v", err))
	}
	return hex.EncodeToString(b)
}
