// Package storage abstracts private object storage (spec §16.4): all
// sensitive documents live in private buckets and are accessed through
// short-lived signed URLs only (ADR 0006). The local adapter writes to
// ./data/uploads and serves files through the API with HMAC-signed expiring
// URLs; the R2 adapter is the production target (config-gated, TODO).
package storage

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"

	"proguidegh/api/internal/platform/httpx"
	"strings"
	"time"
)

// SignedURLTTL is the default lifetime of generated URLs (spec §15.3:
// short-lived).
const SignedURLTTL = 15 * time.Minute

// Store is the signed-URL object storage interface.
type Store interface {
	// PresignUpload returns a URL a client can PUT the object to, and the
	// object key that must be stored alongside the document metadata.
	PresignUpload(ctx context.Context, prefix, contentType string) (key, uploadURL string, err error)
	// PresignGet returns a short-lived URL to download the object.
	PresignGet(ctx context.Context, key string) (string, error)
	// Put stores server-generated bytes under key (receipts, reports) — the
	// server-side counterpart to client presigned uploads.
	Put(ctx context.Context, key, contentType string, data []byte) error
	// Delete removes an object. Required for erasure of guide verification
	// documents on account deletion (Act 843; spec §1.2 #7 — sensitive
	// documents must not outlive the account). Deleting an object that is
	// already gone is not an error: erasure must be idempotent so a retried
	// deletion cannot fail after the database rows are already cleared.
	Delete(ctx context.Context, key string) error
}

// ValidateKey rejects keys that could escape the storage root.
func ValidateKey(key string) error {
	if key == "" || strings.Contains(key, "..") || strings.HasPrefix(key, "/") ||
		strings.Contains(key, "\\") {
		return errors.New("storage: invalid object key")
	}
	return nil
}

// ---------------------------------------------------------------------------
// Local dev adapter
// ---------------------------------------------------------------------------

// Local stores objects under dir on disk and signs URLs with HMAC-SHA256.
// Signed GET/PUT URLs are served by Handler (mounted at /api/v1/files).
type Local struct {
	dir    string
	secret []byte
	// BasePath is the URL path prefix the file handler is mounted under.
	BasePath string
	now      func() time.Time
}

// NewLocal builds the local adapter, creating dir when missing.
func NewLocal(dir, secret string) (*Local, error) {
	if secret == "" {
		return nil, errors.New("storage: signing secret required")
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return nil, fmt.Errorf("storage: create dir: %w", err)
	}
	return &Local{dir: dir, secret: []byte(secret), BasePath: "/api/v1/files", now: time.Now}, nil
}

// NewKey generates a collision-resistant object key under prefix.
func NewKey(prefix string) (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("storage: key entropy: %w", err)
	}
	prefix = strings.Trim(prefix, "/")
	if prefix == "" {
		return hex.EncodeToString(b), nil
	}
	return prefix + "/" + hex.EncodeToString(b), nil
}

// escapeKey URL-escapes each path segment of a validated key while
// preserving the "/" separators, so the served request path matches the
// key byte-for-byte after ServeMux wildcard decoding (r.PathValue).
func escapeKey(key string) string {
	segs := strings.Split(key, "/")
	for i, s := range segs {
		segs[i] = url.PathEscape(s)
	}
	return strings.Join(segs, "/")
}

// PresignUpload returns an HMAC-signed PUT URL under BasePath.
func (l *Local) PresignUpload(_ context.Context, prefix, contentType string) (string, string, error) {
	key, err := NewKey(prefix)
	if err != nil {
		return "", "", err
	}
	if contentType == "" {
		contentType = "application/octet-stream"
	}
	exp := l.now().Add(SignedURLTTL).Unix()
	u := fmt.Sprintf("%s/%s?expires=%d&ct=%s&sig=%s",
		l.BasePath, escapeKey(key), exp, url.QueryEscape(contentType), l.sign("PUT", key, exp, contentType))
	return key, u, nil
}

// PresignGet returns an HMAC-signed GET URL under BasePath.
func (l *Local) PresignGet(_ context.Context, key string) (string, error) {
	if err := ValidateKey(key); err != nil {
		return "", err
	}
	exp := l.now().Add(SignedURLTTL).Unix()
	u := fmt.Sprintf("%s/%s?expires=%d&sig=%s",
		l.BasePath, escapeKey(key), exp, l.sign("GET", key, exp, ""))
	return u, nil
}

// Put stores server-generated bytes under key on local disk.
func (l *Local) Put(_ context.Context, key, _ string, data []byte) error {
	if err := ValidateKey(key); err != nil {
		return err
	}
	path := l.pathFor(key)
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("storage: create dir: %w", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("storage: write object: %w", err)
	}
	return nil
}

// Delete removes the object from local disk. A file that is already gone is
// not an error — erasure has to be idempotent, so a retried account deletion
// cannot fail after the database rows are already cleared.
func (l *Local) Delete(_ context.Context, key string) error {
	if err := ValidateKey(key); err != nil {
		return err
	}
	if err := os.Remove(l.pathFor(key)); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("storage: delete object: %w", err)
	}
	return nil
}

// Handler serves and receives objects for the local adapter: it enforces the
// HMAC signature and expiry on every request so files never become public
// (stop condition 8). Mount at "PUT /api/v1/files/{key...}" and
// "GET /api/v1/files/{key...}".
func (l *Local) Handler() http.Handler {
	put := http.HandlerFunc(l.servePut)
	get := http.HandlerFunc(l.serveGet)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPut:
			put.ServeHTTP(w, r)
		case http.MethodGet:
			get.ServeHTTP(w, r)
		default:
			httpx.WriteError(w, r, http.StatusMethodNotAllowed, "METHOD_NOT_ALLOWED", "method not allowed", nil)
		}
	})
}

func (l *Local) servePut(w http.ResponseWriter, r *http.Request) {
	key := r.PathValue("key")
	exp, err := l.verify(r, http.MethodPut, key)
	if err != nil {
		httpx.WriteError(w, r, http.StatusForbidden, "INVALID_SIGNATURE", err.Error(), nil)
		return
	}
	ct := r.URL.Query().Get("ct")
	if ct == "" {
		ct = r.Header.Get("Content-Type")
	}
	if ct == "" {
		ct = "application/octet-stream"
	}
	// Bind the signature to the declared content type.
	if !hmac.Equal([]byte(l.sign(http.MethodPut, key, exp.Unix(), ct)), []byte(r.URL.Query().Get("sig"))) {
		httpx.WriteError(w, r, http.StatusForbidden, "INVALID_SIGNATURE", "invalid upload signature", nil)
		return
	}
	_ = exp

	path := l.pathFor(key)
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		httpx.WriteError(w, r, http.StatusInternalServerError, "INTERNAL", "could not store file", nil)
		return
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		httpx.WriteError(w, r, http.StatusInternalServerError, "INTERNAL", "could not store file", nil)
		return
	}
	defer f.Close() //nolint:errcheck
	// Cap uploads at 16 MiB; larger files should use multipart (Phase 2+).
	if _, err := io.Copy(f, io.LimitReader(r.Body, 16<<20)); err != nil {
		httpx.WriteError(w, r, http.StatusInternalServerError, "INTERNAL", "could not store file", nil)
		return
	}
	w.WriteHeader(http.StatusCreated)
}

func (l *Local) serveGet(w http.ResponseWriter, r *http.Request) {
	key := r.PathValue("key")
	if _, err := l.verify(r, http.MethodGet, key); err != nil {
		httpx.WriteError(w, r, http.StatusForbidden, "INVALID_SIGNATURE", err.Error(), nil)
		return
	}
	f, err := os.Open(l.pathFor(key))
	if err != nil {
		httpx.WriteError(w, r, http.StatusNotFound, "NOT_FOUND", "object not found", nil)
		return
	}
	defer f.Close() //nolint:errcheck
	if ct := mime.TypeByExtension(filepath.Ext(key)); ct != "" {
		w.Header().Set("Content-Type", ct)
	}
	_, _ = io.Copy(w, f)
}

func (l *Local) verify(r *http.Request, method, key string) (time.Time, error) {
	if err := ValidateKey(key); err != nil {
		return time.Time{}, err
	}
	q := r.URL.Query()
	exp, err := strconv.ParseInt(q.Get("expires"), 10, 64)
	if err != nil {
		return time.Time{}, errors.New("missing or malformed expiry")
	}
	expiresAt := time.Unix(exp, 0)
	if l.now().After(expiresAt) {
		return expiresAt, errors.New("signed URL expired")
	}
	if !hmac.Equal([]byte(l.sign(method, key, exp, q.Get("ct"))), []byte(q.Get("sig"))) {
		return expiresAt, errors.New("invalid signature")
	}
	return expiresAt, nil
}

func (l *Local) sign(method, key string, expires int64, contentType string) string {
	h := hmac.New(sha256.New, l.secret)
	fmt.Fprintf(h, "%s\n%s\n%d\n%s", method, key, expires, contentType)
	return hex.EncodeToString(h.Sum(nil))
}

func (l *Local) pathFor(key string) string {
	// ValidateKey guarantees no traversal; Join + Clean is belt-and-braces.
	return filepath.Join(l.dir, filepath.Clean("/"+key))
}

// ---------------------------------------------------------------------------
// R2 adapter (production) — config-gated stub
// ---------------------------------------------------------------------------

// R2Config carries the Cloudflare R2 settings (.env.example: R2_*).
type R2Config struct {
	Endpoint        string // R2_ENDPOINT
	AccessKeyID     string // R2_ACCESS_KEY_ID
	SecretAccessKey string // R2_SECRET_ACCESS_KEY
	BucketPrivate   string // R2_BUCKET_PRIVATE
}

// R2 will implement Store against Cloudflare R2 (S3 API) with presigned
// URLs. TODO(phase-2): implement with AWS SigV4 presigning; until then NewR2
// fails fast when production storage is requested, and deployments keep
// using the local adapter only outside production.
type R2 struct {
	cfg R2Config
}

// NewR2 validates the config and returns the adapter.
func NewR2(cfg R2Config) (*R2, error) {
	if cfg.Endpoint == "" || cfg.AccessKeyID == "" || cfg.SecretAccessKey == "" || cfg.BucketPrivate == "" {
		return nil, errors.New("storage: R2_ENDPOINT, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY and R2_BUCKET_PRIVATE are required")
	}
	return &R2{cfg: cfg}, nil
}

// PresignUpload is not yet implemented for R2.
func (r *R2) PresignUpload(context.Context, string, string) (string, string, error) {
	return "", "", errors.New("storage: R2 adapter not implemented yet (TODO phase-2: SigV4 presigned PUT)")
}

// PresignGet is not yet implemented for R2.
func (r *R2) PresignGet(context.Context, string) (string, error) {
	return "", errors.New("storage: R2 adapter not implemented yet (TODO phase-2: SigV4 presigned GET)")
}

// Put is not yet implemented for R2.
func (r *R2) Put(context.Context, string, string, []byte) error {
	return errors.New("storage: R2 adapter not implemented yet (TODO phase-2: SigV4 PutObject)")
}

// Delete is not yet implemented for R2.
func (r *R2) Delete(context.Context, string) error {
	return errors.New("storage: R2 adapter not implemented yet (TODO phase-2: SigV4 DeleteObject)")
}

// Compile-time proof both adapters still satisfy Store.
var (
	_ Store = (*Local)(nil)
	_ Store = (*R2)(nil)
)
