"use client";
import { use, useState } from "react";
import Link from "next/link";
import { Alert, Button, Input } from "@proguidegh/ui";
import { AdminAuthShell } from "../../components/AdminAuthShell";
import { api, errorMessage } from "../../lib/api";
export default function AcceptInvitationPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); if (password !== confirm) { setError("Passwords do not match."); return } setPending(true); try { await api("/auth/invitations/accept", { method: "POST", body: { token: decodeURIComponent(token), password }, skipRefreshRetry: true }); setDone(true) } catch (err) { setError(errorMessage(err, "This invitation could not be accepted.")) } finally { setPending(false) } }
  return <AdminAuthShell>{done ? <div className="admin-auth__form"><header><p>Access approved</p><h1>Your command center account is ready.</h1><span>Sign in with the password you just created. Multi-factor setup may be required for your role.</span></header><Alert tone="success" title="Invitation accepted"><p>Your one-time invitation has been securely consumed.</p></Alert><Link className="gg-button gg-button--primary" href="/login">Continue to sign in</Link></div> : <div className="admin-auth__form" aria-busy={pending}><header><p>Administrator invitation</p><h1>Create your secure access.</h1><span>Choose a strong password to finish joining the operations team.</span></header>{error && <Alert tone="error" title="Could not accept invitation"><p>{error}</p></Alert>}<form onSubmit={submit}><Input label="Create password" name="password" type="password" autoComplete="new-password" minLength={8} required value={password} onChange={(event) => setPassword(event.target.value)} disabled={pending} hint="Use at least 8 characters." /><Input label="Confirm password" name="confirm" type="password" autoComplete="new-password" minLength={8} required value={confirm} onChange={(event) => setConfirm(event.target.value)} disabled={pending} /><div className="admin-auth__submit"><Button type="submit" disabled={pending}>{pending ? "Securing account…" : "Accept invitation"}</Button><small><i aria-hidden="true" /> Single-use encrypted link</small></div></form></div>}</AdminAuthShell>;
}
