"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { createPortal } from "react-dom";
import { APP_URL } from "../lib/content";
import { Logo } from "./logo";

const links = [
  ["Destinations", "/destinations", "pin"], ["Safety", "/safety", "shield"], ["Pricing", "/pricing", "tag"], ["Become a guide", "/become-a-guide", "badge"], ["About", "/about", "info"], ["Contact", "/contact", "mail"],
] as const;
function Icon({ name }: { name: string }) { const paths: Record<string,React.ReactNode> = { pin:<><path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></>,shield:<><path d="M12 3 5 6v5c0 4.6 2.8 8.1 7 10 4.2-1.9 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-5"/></>,tag:<><path d="M4 7.5V4h3.5L20 16.5 16.5 20 4 7.5Z"/><circle cx="7.5" cy="7.5" r="1"/></>,badge:<><circle cx="12" cy="9" r="5"/><path d="m8.5 13-1 8 4.5-2.5 4.5 2.5-1-8"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7.5v.1"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></> }; return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>; }
export function MarketingMobileNav() {
  const [open,setOpen]=useState(false); const pathname=usePathname(); const panelRef=useRef<HTMLDivElement>(null); const triggerRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{ if(!open)return; const previous=document.body.style.overflow; document.body.style.overflow="hidden"; const onKey=(event:KeyboardEvent)=>{ if(event.key==="Escape"){setOpen(false);triggerRef.current?.focus();} if(event.key!=="Tab")return; const nodes=panelRef.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled])'); if(!nodes?.length)return; const first=nodes.item(0),last=nodes.item(nodes.length-1); if(!first||!last)return; if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();} }; document.addEventListener("keydown",onKey); return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",onKey);}; },[open]);
  const drawer = open ? <div ref={panelRef} className="mobile-drawer" role="dialog" aria-modal="true" aria-label="Menu"><div className="mobile-drawer__glow" aria-hidden="true"/><header><Link href="/" onClick={()=>setOpen(false)} aria-label="ProGuideGH home"><Logo/></Link><button type="button" aria-label="Close menu" onClick={()=>{setOpen(false);triggerRef.current?.focus();}}>×</button></header><nav aria-label="Mobile navigation"><ul>{links.map(([label,href,icon],index)=>{const active=pathname===href||pathname.startsWith(`${href}/`);return <li key={href}><Link href={href} aria-current={active?"page":undefined} onClick={()=>setOpen(false)}><span className="mobile-drawer__index" aria-hidden="true">{String(index+1).padStart(2,"0")}</span><span className="mobile-drawer__icon" aria-hidden="true"><Icon name={icon}/></span><strong>{label}</strong><i aria-hidden="true">↗</i></Link></li>;})}<li className="mobile-drawer__signin"><a href={`${APP_URL}/login`}><span>Account access</span><strong>Sign in to ProGuideGH</strong><i aria-hidden="true">→</i></a></li></ul></nav><a className="mobile-drawer__cta" href={`${APP_URL}/search`}>Find a certified guide <b aria-hidden="true">↗</b></a></div> : null;
  return <><button ref={triggerRef} className="nav__menu-button" type="button" aria-label={open?"Close menu":"Open menu"} aria-expanded={open} aria-haspopup="dialog" onClick={()=>setOpen(current=>!current)}><span/><span/></button>{drawer ? createPortal(drawer,document.body) : null}</>;
}
